### ISSUE TITLE
Activity tracker section functional update

### ISSUE THREAD

**Issue by Chaitanya-05** [sanjukumari-tech/Baidu-Bandits_072#73]
- [ ] update your from functionality to update state 
- [ ] ok clicking update it should update redux state as well as call updateData function and update firebase data
- [ ] add next week button which will clear the data from all week 
- [ ] update your teamwhen complted, check thoroughly when done
